### ISSUE TITLE
Resources bugs

### ISSUE THREAD

**Issue by Sageblatt** [Amisto/the_ark#16]
~~1) В методах setComponentsToUsed, setUsedToJunk используется id, который, судя по всему является номером службы. Если это действительно так, то int нужно заменить на соответствующий enum Services.~~
~~2) Из-за сырых поинтеров и new на org_res и not_org_res и отсутствия деструктора течёт память.~~
3) TechnicalService::efficiencyJunkToRefuse и два других метода, выдающих эффективность завязаны на maxStaff, поэтому в самом начале возвращают nan, что ломает число ресурсов.
4) EmergencyService.cpp 109 строка при первом вызове ломает used у ресурсов.

**Comment by karimvafin** [comment]
checked methods of Technical service, fixed, field maxStaff has to be correct value now
