### ISSUE TITLE
Problems with Technical Service

### ISSUE THREAD

**Issue by klauchek** [Amisto/the_ark#2]
functions 

`unsigned int TechnicalService::getResourceDemand() {

}

unsigned int TechnicalService::getResourcePriority() {}

unsigned int TechnicalService::getStaffDemand() {}

unsigned int TechnicalService::getStaffPriority() {}

bool TechnicalService::changeStaff(int delta) {}

bool TechnicalService::changeResources(int delta) {}`

should return a value. Build errors. @karimvafin

**Comment by Amisto** [comment]
Fixed by commit 76485c6823c94f8110bad881b9c01cae3f8254d3
