### ISSUE TITLE
Invalid init of Population due to incorrect number_staff method

### ISSUE THREAD

**Issue by Sageblatt** [Amisto/the_ark#3]
https://github.com/Amisto/the_ark/blob/main/Population.cpp#L44
returns 0 every time while being in used in Population::init

**Comment by Amisto** [comment]
It is probably better to manage number_staff inside the Population class, without addressing particular services, just through container sizes.

**Comment by Amisto** [comment]
It is kinda working now)))

**Comment by Amisto** [comment]
But no, lol, we still have to manage this Service::n_staff or delete it.
