### ISSUE TITLE
Invalid output issues

### ISSUE THREAD

**Issue by Sageblatt** [Amisto/the_ark#9]
Input 100 100 100 100 100 100 100 100 100
~~1) getState value in EmergencyService method returns 2.09511e+09 sometimes @klauchek~~
2) strange values in Compon and Used columns, seems like unsigned int goes lower than 0 @jesuslovesyoutoday

**Comment by Sageblatt** [comment]
~~1st one is fixed;~~

**Comment by Amisto** [comment]
2nd one is also fixed.
